apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: my-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: my-cluster-rolebinding
subjects:
  - name: my-service-account
    kind: ServiceAccount
    apiGroup: rbac.authorization.k8s.io
roleRef:
  - name: my-cluster-role
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io