apiVersion: v1
kind: ConfigMap
metadata:
  name: configMap-backend
  namespace: my-namespace
data:
  db-port: "87"
  api-port: "4242"
  host: db-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configMap-frontend
  namespace: my-namespace
data:
  api-url: http://db-service:4242