apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: my-namespace
  labels:
    app: myapp
    tier: database
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      tier: database
  template:
    metadata:
      name: mongodb
      labels:
        app: myapp
        tier: database
    spec:
      containers:
        - name: database
          image: lovelyfossil/mongo-server
          resources:
            limits:
              cpu: 1
              memory: 100Mi
          volumeMounts:
            - name: volume
              mountPath: "/db/data"
          ports:
          - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: my-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  namespace: my-namespace
  labels:
    app: myapp
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      tier: backend
  template:
    metadata:
      name: express
      labels:
        app: myapp
        tier: backend
    spec:
      containers:
        - name: backend
          image: lovelyfossil/api-server:kube
          resources:
            limits:
              cpu: 1
              memory: 100Mi
          ports:
            - containerPort: 4242
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: configMap-backend
                  key: host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: configMap-backend
                  key: db-port
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: configMap-backend
                  key: api-port
          livenessProbe:
            httpGet:
              path: /
              port: ${API_PORT}
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 45
          readinessProbe:
            httpGet:
              path: /api/notes
              port: ${API_PORT}
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 45
          serviceAccountName: my-service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  namespace: my-namespace
  labels:
    app: myapp
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      tier: frontend
  template:
    metadata:
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
      - name: myapp
        image: lovelyfossil/react-app
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_API_URL
            valueFrom:
              configMapKeyRef:
                name: configMap-frontend
                key: api-url
