apiVersion: v1
kind: Namespace
spec:
  name: my-namespace
---
apiVersion: v1
kind: LimitRange
metadata:
  name: my-default-limit
  namespace: my-namespace
spec:
  limits:
  - default:
      memory: 100Mi
      cpu: 100m
    defaultRequest:
      memory: 50Mi
      cpu: 50m
  - max:
      memory: 256Mi
      cpu: 500m
  - min:
      memory: 50Mi
      cpu: 50m
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota
  namespace: my-namespace
spec:
  hard:
    pods: 14
    secrets: 1
    configmaps: 2
    services: 3