apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: my-namespace
  name: my-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
        watch
        list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: my-rolebinding
  namespace: my-namespace
subjects:
  - kind: User
    name: test
    apiGroup: rbac.authorization.k8s.io
roleRef:
  - kind: Role
    name: my-role
    apiGroup: rbac.authorization.k8s.io
---
